name: LightningItems
version: 0.2
author: Jake (John) Moe (JakesAddress@gmail.com)
main: me.jakemoe.LightningItems.Main
website: https://github.com/JakeMoe/LightningItems
database: false

commands:
  lightningitem:
    aliases: li
    description: drops an item
    usage: <command>
